-- Températures Les Sapins — V3
-- La base Supabase de production est déjà configurée par migrations.
-- Ce fichier est conservé uniquement pour éviter qu'une ancienne version du schéma V2 reste dans le dépôt GitHub.
-- Ne pas l'exécuter manuellement sur le projet de production.
